version: 2.1

workflows:
  run-collection-workflow:
    jobs: 
      - newman-collection-run

jobs:
  newman-collection-run:
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - run:
          name: Install Newman
          command: npm install -g newman

      - run:
          name: Run collection
          command: newman run "https://api.getpostman.com/collections/${COLLECTION_ID}?apikey=${POSTMAN_API_KEY}" 
          
