version: 2.1

workflows:
  run-collection-workflow:
    jobs: 
      - newman-test-collection:
         filters:
          branches:
            only: main

jobs:
  newman-test-collection:
    docker:
      - image: postman/newman:latest
    steps:
      - checkout
      - run:
          name: Run collection
          command: newman run "postmanCollections/Simple-Books-Postman.json"

