version: 2.1

workflows:
  run-collection-workflow:
    jobs: 
      - newman-collection-run

jobs:
  newman-collection-run:
    docker:
      - image: node:16-alpine
    steps:
      - checkout
      - run:
          name: Install Newman and postman cloud reporter
          command: npm install -g newman newman-reporter-htmlextra

      - run:
          name: Run collection and upload results
          command: newman run "https://api.getpostman.com/collections/${COLLECTION_ID}?apikey=${POSTMAN_API_KEY}" --folder "Register API Client" -d test-results/simple-books-data - Copy.csv -r cli,htmlextra --reporter-htmlextra-export test-results/result.html
          
          #command: newman run "https://api.getpostman.com/collections/${COLLECTION_ID}?apikey=${POSTMAN_API_KEY}" 
          
      - store_test_results:
          path: test-results    
      
