version: 2.1

workflows:
  run-collection-workflow:
    jobs: 
      - newman-test-collection

jobs:
  newman-test-collection:
    docker:
      - image: postman/newman:latest
    steps:
      - checkout
      - run:
          name: Run collection
          command: newman run "https://api.getpostman.com/collections/${COLLECTION_ID}?apikey=${POSTMAN_API_KEY}" 
          
