#test branch config
version: 2.1

workflows:
  check-postman-test-commits-workflow:
    jobs: 
      - test-branch-collection:
          filters:
            branches:
              only: test

jobs:
  test-branch-collection:
    docker:
      - image: postman/newman:latest
    steps:
      - checkout
      - run:
          name: Run collection
          command: newman run "simple-books-api/postmanCollections/Simple-Books-Postman.json" --folder "API Status"
          
